apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: bbadpipelinetest 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bbadpipelinetest 
    spec:
      containers:
        - name: bbadpipelinetest 
          image: mycontainertestkk.azurecr.io/bbadpipelinetest
          ports:
          - containerPort: 8080